#!/usr/bin/env python3
"""Helper script for finding issues refed in commits."""
import logging
import os
import sys

import git

logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        logging.error(
            "You need to pass exactly two arguments: commitA, commitB")
        sys.exit(1)

    commit_a = sys.argv[1]
    commit_b = sys.argv[2]

    curr_dir = os.getcwd()
    g = git.Git(curr_dir)
    logs = g.log("%s..%s" % (commit_a, commit_b)).split("\n")

    refs = set()
    for line in logs:
        if "Refs" not in line:
            continue

        if "arrikto/" not in line:
            continue

        refs.add(line.strip())

    refs = list(refs)
    refs.sort()
    for item in refs:
        print(item)
